### ISSUE TITLE
Discord Dart - Docs

### ISSUE THREAD

**Issue by developerCodex** [Hackzzila/Discord-Dart#10]
You need a website or something for docs, or I lost them if you had docs, lol.

**Comment by datitisev** [comment]
https://www.dartdocs.org/documentation/discord/0.14.2/

**Comment by developerCodex** [comment]
Oh, okay thank you!

**Comment by Hackzzila** [comment]
https://www.dartdocs.org/documentation/discord/latest/ is better.
The other one is locked down to version v0.14.2
