### ISSUE TITLE
Duplicate documentation links?

### ISSUE THREAD

**Issue by AluminiumTech** [Hackzzila/Discord-Dart#12]
On the site for documentation, for each version there are 2 links to the same documentation.

And yet they both lead to the same documentation discord library page.

This is annoying......

![discord](https://cloud.githubusercontent.com/assets/14107316/19626060/1a4989ae-995b-11e6-8342-23cbad446d66.PNG)

**Comment by Hackzzila** [comment]
That is because of how I handle code for dart vm and the browser. It is "fixed" in indev.
