### ISSUE TITLE
Is this a 1:1 port of Discord.js?

### ISSUE THREAD

**Issue by matanlurey** [Hackzzila/Discord-Dart#2]
Just wondering because I was starting on this too and would love to collaborate - but also want to go a bit more dart idiomatic than a full port.

**Comment by Hackzzila** [comment]
No, it is going to be similar, but not identical. I don't want it to be a port, I want it to be a quality dart lib. And I would be happy to have a collaborator!

**Comment by Gawdl3y** [comment]
I'm one of the Discord.js devs, and I'm very interested in this library. I originally suggested @Hackzzila make it object-oriented like d.js is, which he did. That, of course, makes it strikingly resemblant, but I don't think it should be a direct port. Definitely make use of Dart's features and capabilities to their full extent.

**Comment by matanlurey** [comment]
Nice! 

I work on the Angular Dart and [Dart](https://github.com/dart-lang) team at Google, and I've love to take any feedback from you @Hackzzila or @Gawdl3y.

I'd like to do a couple things:

- Use a higher-level HTTP library (I was working on https://github.com/matanlurey/seltzer)
- Support both browser and server/CLI clients
- Eventually create an actual Bot application that uses this API and host it on Google Managed VM

If this sounds interesting, I'd love to contribute. I have some experience writing bots for battle.net back when that was a thing.

**Comment by Hackzzila** [comment]
@matanlurey I would love to have you as a contributor! You should get in touch with me on Discord (I am Hk. on the Discord Dart server).

**Comment by matanlurey** [comment]
@Hackzzila Great, I'm on.
