### ISSUE TITLE
Reproduce integration test (discord.dart) locally?

### ISSUE THREAD

**Issue by matanlurey** [Hackzzila/Discord-Dart#4]
I added a bot token I created specifically to test this API, but it doesn't seem to work. I get a connection, but never get a 'ready' event. From what I can tell, I might need to belong to a specific guild or have some other configuration for my test account to run.

Any idea?

**Comment by Hackzzila** [comment]
You should be receiving ready, unless it is a user bot (user bots are broken rn). But the test is not reproducible without edits and might be removed anyways.

**Comment by matanlurey** [comment]
Fair enough. I'll close this and open another issue to add a new integration test.
